name = "gs904_transit"
author = "WornOutWanderer"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "84E15F18F61A86FF977605B35E6FFD683C6261E07797BC450EBD347A3F39D9F8"

[versions]
fabric = "0.15.2"
minecraft = "1.19.2"
